Update Semaphore configuration

diff --git a/.semaphore/semaphore.yml b/.semaphore/semaphore.yml
--- a/.semaphore/semaphore.yml
+++ b/.semaphore/semaphore.yml
@@ -15,22 +15,27 @@ blocks:
           - checkout
           - PROJECT_DIR=$(ls -d */ | head -n1 | sed 's/\/$//')
           - cd $PROJECT_DIR
-          - "if [ -d \"app\" ]; then\n  echo \"✅ app found in root\"\nelse\n  echo \"\U0001F50D Searching for app folder...\"\n  APP_PATH=$(find . -type d -name \"app\" -not -path \"*/node_modules/*\" | head -n1)\n  if [ -n \"$APP_PATH\" ]; then\n    echo \"✅ app found at $APP_PATH\"\n    cd $APP_PATH/..\n  else\n    echo \"❌ app folder not found!\"\n    ls -la\n    exit 1\n  fi\nfi\n"
-          - 'cache restore node-modules-$SEMAPHORE_GIT_BRANCH-$(checksum app/package-lock.json), node-modules'
-          - cd app && npm ci
-          - cache store node-modules-$SEMAPHORE_GIT_BRANCH-$(checksum app/package-lock.json) app/node_modules
+          - "if [ -d \"app\" ]; then\n  echo \"✅ app found in root\"\n  cd app\nelse\n  echo \"\U0001F50D Searching for app folder...\"\n  APP_PATH=$(find . -type d -name \"app\" -not -path \"*/node_modules/*\" | head -n1)\n  if [ -n \"$APP_PATH\" ]; then\n    echo \"✅ app found at $APP_PATH\"\n    cd $APP_PATH\n  else\n    echo \"❌ app folder not found!\"\n    ls -la\n    exit 1\n  fi\nfi\n"
+          - pwd
+          - 'cache restore node-modules-$SEMAPHORE_GIT_BRANCH-$(checksum package-lock.json), node-modules'
+          - npm ci
+          - cache store node-modules-$SEMAPHORE_GIT_BRANCH-$(checksum package-lock.json) node_modules
       jobs:
         - name: Lint and Test
           commands:
-            - PROJECT_DIR=$(ls -d */ | head -n1 | sed 's/\/$//')
-            - cd $PROJECT_DIR
             - |
-              if [ -d "app" ]; then
-                cd app
-              else
-                APP_PATH=$(find . -type d -name "app" -not -path "*/node_modules/*" | head -n1)
-                cd $APP_PATH
+              if [ ! -f "package.json" ]; then
+                PROJECT_DIR=$(ls -d */ | head -n1 | sed 's/\/$//')
+                cd $PROJECT_DIR
+                if [ -d "app" ]; then
+                  cd app
+                else
+                  APP_PATH=$(find . -type d -name "app" -not -path "*/node_modules/*" | head -n1)
+                  cd $APP_PATH
+                fi
               fi
+            - pwd
+            - ls -la
             - npm run lint
             - npm test -- --watchAll=false
   - name: Push Docker image
